<a href="https://colab.research.google.com/github/BOBcheeto/Lab-2/blob/main/week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? BOB
Welcome, BOB!


In [ ]:
# complete your program here
f = float(input('Please enter the temperature in Fahrenheit: '))

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(str(f)+'F is '+str(c)+' in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 10
10.0
10.0F is -12.222222222222221 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
c = int(input('Please enter the temperature in Celcius: '))

print(c)

f = c/(5/9)+32


print(f)

Please enter the temperature in Celcius: 10
10
50.0


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d = float(input('Please enter the temperature: '))
m = input('Is this in Celsius or Fahrenheit? (C or F?) ')

def tempConverter(temp, type):
  temp = temp
  if type.upper() == "C":
    temp = round(temp/(5/9)+32, 2)
    return f'{temp} in Fahrenheit'
  elif type.upper() == "F":
    temp = round((temp - 32) * 5/9, 2)
    return f'{temp} in Celsius'

  return 'error'

print(tempConverter(d, m))

Please enter the temperature: 100
Is this in Celsius or Fahrenheit? (C or F?) f
37.78 in Celsius


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
print(len(sentence))

48


In [ ]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[9: -9])

heap. Show me the code - Linus


In [ ]:
# Given the sentence, output a list of words in lowercase (without punctuations).
list = []
sentence_no_punc_lower = sentence.replace('.', '').replace('-', '').replace(' ', '').lower()
for i in range(len(sentence_no_punc_lower)):
    list.append(sentence_no_punc_lower[i])

list

['t',
 'a',
 'l',
 'k',
 'i',
 's',
 'c',
 'h',
 'e',
 'a',
 'p',
 's',
 'h',
 'o',
 'w',
 'm',
 'e',
 't',
 'h',
 'e',
 'c',
 'o',
 'd',
 'e',
 'l',
 'i',
 'n',
 'u',
 's',
 't',
 'o',
 'r',
 'v',
 'a',
 'l',
 'd',
 's']

In [ ]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
count = 0
for i, ch in enumerate(sentence.lower()):
  if ch in vowels:
    count += 1

print(f'The totla number of vowels is {count}')

The totla number of vowels is 13


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
list = []
for i in range(len(sentence)):
  for v in vowels:
    if sentence[i] == v:
      list.append(i)

print(f'The positions (indexes) of all vowels in the sentence are {list}')

The positions (indexes) of all vowels in the sentence are [1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
  cubes.append(i**3)

print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Use list comprehension to create the same list
cubes_lc = [i**3 for i in range(5)]
print(cubes_lc)

[0, 1, 8, 27, 64]


In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
positions = [i for i, ch in enumerate(sentence) if ch in vowels]
print(positions)

[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = int(input('How many numbers do you want? '))

# add your code here
if n < 0:
  print('enter a positive int')
elif n == 1:
  fibonacci = [0]
elif n == 2:
  fibonacci = [0, 1]
elif n > 2:
  fibonacci = [0, 1]
  for i in range(2,n):
    fibonacci.append(fibonacci[i-1] + fibonacci[i-2])

print(fibonacci)

How many numbers do you want? 10
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
d = {'Pfizer': .95, 'Moderna': .95, 'AstraZeneca': .72, 'Johnson & Johnson': .66}

In [ ]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(f'{v}\'s efficacy is: {d[v]}')

Which vaccine? Pfizer
Pfizer's efficacy is: 0.95


In [ ]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
d['Sputnik V'] = .914

In [ ]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
d['Sinovac'] = .5038

In [ ]:
# Print vaccines with efficacy lower than 90%.
low_efficacy_vaccines = {}
for vaccine, efficacy in d.items():
    if efficacy < 0.90:
        low_efficacy_vaccines[vaccine] = efficacy

print("Vaccines with efficacy lower than 90%:")
for vaccine, efficacy in low_efficacy_vaccines.items():
    print(f"{vaccine}: {efficacy:.2%}")

Vaccines with efficacy lower than 90%:
AstraZeneca: 72.00%
Johnson & Johnson: 66.00%
Sinovac: 50.38%


In [ ]:
# delete the Sinovac vaccine from the dictionary.
del d['Sinovac']

In [ ]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
for ch in sentence:
  if ch != ' ':
    ch_dict[ch] = ch_dict.get(ch, 0) + 1

# print the dictionary
print(f'the occurrence of each alphabet (no space \' \') in this sentence is: {ch_dict}')

the occurrence of each alphabet (no space ' ') in this sentence is: {'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [ ]:
import numpy as np

In [ ]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([i for i in range(2, 42, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [ ]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([i+1 for i in range(0, 40, 2)])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [ ]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.arange(100).reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(loc=0, scale=1, size=(10, 10))
M.shape
M

array([[-2.01429337e+00, -5.87687922e-01, -1.16819514e+00,
        -1.04315375e-01, -5.14018955e-01, -1.77694969e-01,
         2.03115210e-01,  1.77188647e+00, -1.07864837e-01,
         1.70556083e+00],
       [-2.70222613e-01,  2.95822808e+00, -2.24572677e+00,
         7.21870131e-01, -1.30983524e+00,  6.53399678e-01,
         1.50991489e+00,  8.68885469e-01,  1.35227640e-01,
         2.09108566e+00],
       [-1.43771871e+00,  8.79375535e-04, -7.37935387e-01,
        -2.05855343e-01, -1.30676159e+00, -1.25143223e+00,
         1.55121792e+00,  2.07531782e-01,  1.61132586e+00,
        -2.87480174e+00],
       [-3.36565825e-02,  1.25690818e+00, -1.03102159e+00,
         1.37900423e+00,  2.92879245e-02, -1.02774134e-01,
        -1.16208715e-01, -1.41485661e+00,  3.59768566e-01,
         3.90150783e-01],
       [-4.64411144e-01, -6.15024227e-01,  1.14959106e+00,
         1.09524401e+00,  8.84786038e-01,  1.16075906e+00,
         7.11022532e-01, -2.18085114e+00, -5.89847088e-01,
        -1.

In [ ]:
count = np.sum(abs(M) > 1)
print(count)

40


In [ ]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = int(input('Row count: '))

# Input the number of columns (input another integer >= 3)
c = int(input('column count: '))

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, size=(r, c))
print(arr)

Row count: 10
column count: 10
[[14 14 11 11 11 17 11 13 11 11]
 [13 18 11 19 14 12 16 11 17 18]
 [18 13 14 15 13 10 16 14 12 11]
 [12 13 19 11 15 11 18 15 13 14]
 [19 18 17 17 14 17 10 11 15 11]
 [18 17 12 12 18 10 10 19 17 12]
 [10 10 10 14 10 14 14 11 12 14]
 [11 15 17 12 16 15 18 19 14 12]
 [18 16 14 10 10 19 10 14 16 14]
 [11 16 12 14 17 12 16 16 17 14]]


In [ ]:
# output the element in the first row and the third column
if (arr.shape[0] >= 1) & (arr.shape[1] >= 3): print(arr[0, 2])

11


In [ ]:
# output the element in the second row and the last column
if (arr.shape[0] >= 2) & (arr.shape[1] >= 1): print(arr[1, -1])

18


In [ ]:
# output the second row of the array
if arr.shape[0] >= 2: print(arr[1, :])

[13 18 11 19 14 12 16 11 17 18]


In [ ]:
# output the second last row of the array
if arr.shape[0] >= 2: print(arr[-2, :])

[18 16 14 10 10 19 10 14 16 14]


In [ ]:
# output the second last column of the array
if arr.shape[1] >= 2: print(arr[:, -2])

[11 17 12 13 15 17 12 14 16 17]


In [ ]:
# output the upper-left 3x3 sub-array
if (arr.shape[0] >= 3) & (arr.shape[1] >= 3): print(arr[:3, :3])

[[14 14 11]
 [13 18 11]
 [18 13 14]]


In [ ]:
# output the bottom-left 3x3 sub-array
if (arr.shape[0] >= 3) & (arr.shape[1] >= 3): print(arr[-3:, :3])

[[11 15 17]
 [18 16 14]
 [11 16 12]]


In [ ]:
# output the upper-right 3x3 sub-array
if (arr.shape[0] >= 3) & (arr.shape[1] >= 3): print(arr[:3, -3:])

[[13 11 11]
 [11 17 18]
 [14 12 11]]


In [ ]:
# output the bottom-right 3x3 sub-array
if (arr.shape[0] >= 3) & (arr.shape[1] >= 3): print(arr[-3:, -3:])

[[19 14 12]
 [14 16 14]
 [16 17 14]]


In [ ]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1,51)
# Reshape A to a 5x10 array in the following format:
A = A.reshape(5, 10)
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]

print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [ ]:
# add a row [51,...,60] to A
A = np.vstack([A, np.arange(51, 61)])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A = A.reshape(2, 3, 10)
print(A)

[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27 28 29 30]]

 [[31 32 33 34 35 36 37 38 39 40]
  [41 42 43 44 45 46 47 48 49 50]
  [51 52 53 54 55 56 57 58 59 60]]]


In [ ]:
# Add 10 to each element of A
A += 10
print(A)

[[[11 12 13 14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]

 [[41 42 43 44 45 46 47 48 49 50]
  [51 52 53 54 55 56 57 58 59 60]
  [61 62 63 64 65 66 67 68 69 70]]]


In [ ]:
# Calculate the square root of each element in A
A = A**0.5
print(A)

[[[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
   4.12310563 4.24264069 4.35889894 4.47213595]
  [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
   5.19615242 5.29150262 5.38516481 5.47722558]
  [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
   6.08276253 6.164414   6.244998   6.32455532]]

 [[6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
   6.8556546  6.92820323 7.         7.07106781]
  [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
   7.54983444 7.61577311 7.68114575 7.74596669]
  [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
   8.18535277 8.24621125 8.30662386 8.36660027]]]


In [ ]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [ ]:
# Print the mean, standard devietion of all numbers in M
print(f"{np.mean(M)}, {np.std(M)}")

-0.13226876211931354, 1.0498734865500112


In [ ]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(f"{np.max(M)}, {np.quantile(M, 0.75)}, {np.median(M)}, {np.quantile(M, 0.25)}, {np.min(M)}")

2.9582280811147075, 0.49287064824726273, -0.10354475492522613, -1.0386079894290658, -2.87480173589922
